apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true

    services:
    - name: lpr-hook
      url: http://logstash-http-to-kafka:8080/
      routes:
      - name: file-uploaded-notify
        strip_path: true
        paths:
        - /file-uploaded-notify

      - name: lpr-available-notify
        strip_path: true
        paths:
        - /lpr-available-notify
  
    plugins:
    - name: http-log
      service: lpr-hook
      config:
        http_endpoint: http://logstash-http-to-kafka.analytic-{{ .Values.envAlias }}.svc.cluster.local:8080/
        method: POST
        timeout: 1000
        keepalive: 1000
        flush_timeout: 2
        retry_count: 15
