apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logstash-http-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP  
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - {{ .Values.domainHttp }}
      secretName: logstash-http-cert
  rules:
    - host: {{ .Values.domainHttp }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: logstash-http-to-kafka
                port:
                  number: 8080
