apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lpr-worker-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: lpr-worker-secret     # name of the k8s Secret to be created
  data:
  - secretKey: LPR_BASE_URL
    remoteRef:
      key: initial-secret
      property: LPR_BASE_URL

  - secretKey: LPR_AUTH_KEY
    remoteRef:
      key: initial-secret
      property: LPR_AUTH_KEY
