apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lpr-api-postgres-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: lpr-api-postgres-secret       # name of the k8s Secret to be created
  data:
  - secretKey: adminPasswordKey
    remoteRef:
      key: initial-secret
      property: PG_CARPARK_API_PASSWORD # In the future we will use from another property
