apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lpr-uploader-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP  
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - {{ .Values.domainLprUpload }}
      - www.{{ .Values.domainLprUpload }}
      secretName: lpr-uploader-cert
  rules:
    - host: {{ .Values.domainLprUpload }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: promftp-{{ .Values.envAlias }}-lpr-uploader
                port:
                  number: 3030
    - host: www.{{ .Values.domainLprUpload }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: promftp-{{ .Values.envAlias }}-lpr-uploader
                port:
                  number: 3030
