apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sftp-users
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: sftp-users            # name of the k8s Secret to be created
  data:
  - secretKey: users.conf
    remoteRef:
      key: initial-secret
      property: SFTP_USERS_CFG
