apiVersion: v2
name: helm-sftp
description: A Helm chart for sftp

type: application

version: 1.0.0

appVersion: "1.0"

dependencies:
  - name: "logstash"
    alias: logstash-http-to-kafka
    condition: logstash-http-to-kafka.enabled
    repository: "https://helm.elastic.co"
    version: "8.5.1"

  - name: "kafka"
    alias: kafka
    condition: kafka.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "25.1.1"
