envAlias: production
domainHttp: lp.promjodd.prom.co.th
domainKafka: kafka-lp.promjodd.prom.co.th

sftp:
  replicaCount: 1
  users:
    - user: prod-test
      bucket: prom-services-ftp
      onlyDir: prod-test

kong:
  replicaCount: 2

promlpr-worker:
  ingress:
    enabled: false

  pods:
    env:
      # To solve ulimit(128) issue
      - name: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"

      - name: JAEGER_AGENT_HOST
        value: "http://tempo.tempo.svc.cluster.local"

      - name: JAEGER_AGENT_PORT
        value: "4317"

      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: "/credentials/gcloud-key.json"

      - name: LPRExecutor__lprBaseUrl
        valueFrom:
          secretKeyRef:
            name: lpr-worker-secret
            key: LPR_BASE_URL
            optional: false

      - name: LPRExecutor__lprAuthKey
        valueFrom:
          secretKeyRef:
            name: lpr-worker-secret
            key: LPR_AUTH_KEY
            optional: false
