envAlias: development
domainHttp: lp.promjodd-dev.prom.co.th
domainKafka: kafka-lp.promjodd-dev.prom.co.th

promlpr-worker:
  ingress:
    enabled: false

  pods:
    env:
      # To solve ulimit(128) issue
      - name: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"

      - name: JAEGER_AGENT_HOST
        value: "http://tempo.tempo.svc.cluster.local"

      - name: JAEGER_AGENT_PORT
        value: "4317"
