kong:
  enabled: true
  replicaCount: 1
  fullnameOverride: kong
  proxy:
    type: ClusterIP

  dblessConfig:
    configMap: kong-config

  env:
    database: "off"

  customEnv:
    DUMMY: "001" #Update this when Kong configuration is changed in order to restart the pods

  ingressController:
    enabled: false # This is required in DB less mode

  admin:
    enabled: true
    type: ClusterIP
    http:
      enabled: true

### Kafka ###
kafka:
  enabled: true
  fullnameOverride: kafka
  provisioning:
    enabled: true
    topics:
      - name: prom-ftp
        partitions: 1
        replicationFactor: 1
        ## https://kafka.apache.org/documentation/#topicconfigs
        config:
          max.message.bytes: 64000

kafka-ui:
  enabled: true
  fullnameOverride: kafka-ui
  existingSecret: kafka-ui-credential
  envs:
    config:
      KAFKA_CLUSTERS_0_NAME: kafka-sftp
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_READONLY: "false"
      AUTH_TYPE: "LOGIN_FORM" #"DISABLED"
      SECURITY_BASIC_ENABLED: "true"

promlpr-worker:
  enabled: true
  nameOverride: lpr-worker

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment
    image:
      name: asia-southeast1-docker.pkg.dev/promrub-personal-use/promlpr/lpr-worker
    volumes:
      - name: gcloud-key
        secret:
          secretName: sftp-gcloud-key
          optional: false
    volumeMounts:
      - name: gcloud-key
        mountPath: /credentials/gcloud-key.json
        subPath: gcloud-key.json
  service:
    enabled: false
    ports: []

promlpr-api:
  enabled: true
  nameOverride: lpr-api

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment
    image:
      name: asia-southeast1-docker.pkg.dev/promrub-personal-use/promlpr/lpr-api
    volumes:
      - name: gcloud-key
        secret:
          secretName: sftp-gcloud-key
          optional: false
    volumeMounts:
      - name: gcloud-key
        mountPath: /credentials/gcloud-key.json
        subPath: gcloud-key.json
  service:
    enabled: true
    ports:
      - port: 8080
        targetPort: 8080
        protocol: TCP
        name: http

postgresql-lpr-api:
  enabled: true
  fullnameOverride: postgresql-lpr-api
  auth:
    database: lpr-api
    existingSecret: lpr-api-postgres-secret
    secretKeys:
      adminPasswordKey: adminPasswordKey

opensearch-cluster:
  enabled: true
  fullnameOverride: opensearch-lpr-api
