apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kafka-ui-credential
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: kafka-ui-credential       # name of the k8s Secret to be created
  data:
  - secretKey: SPRING_SECURITY_USER_NAME
    remoteRef:
      key: initial-secret
      property: KAFKA_UI_USER

  - secretKey: SPRING_SECURITY_USER_PASSWORD
    remoteRef:
      key: initial-secret
      property: KAFKA_UI_PASSWORD
