apiVersion: v1
kind: Service
metadata:
  name: {{ include "sftp-gcs.fullname" . }}
  labels:
    {{- include "sftp-gcs.labels" . | nindent 4 }}
{{- with .Values.sftp.service.annotations }}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  type: {{ .Values.sftp.service.type }}
  ports:
    - name: sftp
      port: {{ .Values.sftp.service.port }}
      targetPort: sftp
      nodePort: {{ .Values.sftp.service.nodePort }}
      protocol: TCP
  selector:
    {{- include "sftp-gcs.selectorLabels" . | nindent 4 }}
