apiVersion: v2
name: helm-sftp
description: A Helm chart for sftp

type: application

version: 1.0.0

appVersion: "1.0"

dependencies:
  - name: "kafka"
    alias: kafka
    condition: kafka.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "22.1.6"

  ### Kong ###
  - name: kong
    version: "2.22.0"
    repository: "https://charts.konghq.com"
    condition: kong.enabled

  - name: "kafka-ui"
    alias: kafka-ui
    condition: kafka-ui.enabled
    repository: "https://provectus.github.io/kafka-ui-charts"
    version: "0.7.4"

  ### PromJodd ###
  - name: "generic-app"
    alias: carpark-worker
    condition: carpark-worker.enabled
    repository: "https://charts.visonneau.fr/"
    version: "0.0.14"

  - name: "generic-app"
    alias: carpark-api
    condition: carpark-api.enabled
    repository: "https://charts.visonneau.fr/"
    version: "0.0.14"

  - name: "generic-app"
    alias: promjodd-web-portal
    condition: promjodd-web-portal.enabled
    repository: "https://charts.visonneau.fr/"
    version: "0.0.14"

  - name: "generic-app"
    alias: lpr-web
    condition: lpr-web.enabled
    repository: "https://charts.visonneau.fr/"
    version: "0.0.14"

  ### pgSQL ###
  - name: "postgresql"
    alias: postgresql-carpark-api
    condition: postgresql-carpark-api.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "12.5.7"

  ### Memcache ###
  - name: "memcached"
    alias: memcached
    condition: memcached.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "6.8.1"
