kong:
  enabled: true
  replicaCount: 1
  fullnameOverride: kong
  proxy:
    type: ClusterIP

  dblessConfig:
    configMap: kong-config

  env:
    database: "off"

  customEnv:
    DUMMY: "001" #Update this when Kong configuration is changed in order to restart the pods

  ingressController:
    enabled: false # This is required in DB less mode

  admin:
    enabled: true
    type: ClusterIP
    http:
      enabled: true

### Kafka ###
kafka:
  enabled: true
  fullnameOverride: kafka
  provisioning:
    enabled: true
    topics:
      - name: prom-ftp
        partitions: 1
        replicationFactor: 1
        ## https://kafka.apache.org/documentation/#topicconfigs
        config:
          max.message.bytes: 64000

kafka-ui:
  enabled: true
  fullnameOverride: kafka-ui
  existingSecret: kafka-ui-credential
  envs:
    config:
      KAFKA_CLUSTERS_0_NAME: kafka-sftp
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_READONLY: "false"
      AUTH_TYPE: "LOGIN_FORM" #"DISABLED"
      SECURITY_BASIC_ENABLED: "true"

carpark-worker:
  enabled: true
  nameOverride: carpark-worker

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment
    image:
      name: asia-southeast1-docker.pkg.dev/promrub-personal-use/promjodd/carpark-worker
    volumes:
      - name: gcloud-key
        secret:
          secretName: sftp-gcloud-key
          optional: false
    volumeMounts:
      - name: gcloud-key
        mountPath: /credentials/gcloud-key.json
        subPath: gcloud-key.json
  service:
    enabled: false
    ports: []

carpark-api:
  enabled: true
  nameOverride: carpark-api

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment
    image:
      name: asia-southeast1-docker.pkg.dev/promrub-personal-use/promjodd/carpark-api
    volumes:
      - name: gcloud-key
        secret:
          secretName: sftp-gcloud-key
          optional: false
    volumeMounts:
      - name: gcloud-key
        mountPath: /credentials/gcloud-key.json
        subPath: gcloud-key.json
  service:
    enabled: true
    ports:
      - port: 8080
        targetPort: 8080
        protocol: TCP
        name: http

postgresql-carpark-api:
  enabled: true
  fullnameOverride: postgresql-carpark-api
  auth:
    database: carpark-api
    existingSecret: carpark-api-postgres-secret
    secretKeys:
      adminPasswordKey: adminPasswordKey

promjodd-web-portal:
  enabled: true
  nameOverride: promjodd-web-portal

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment
    image:
      name: asia-southeast1-docker.pkg.dev/promrub-personal-use/promjodd/promjodd-web-portal
  service:
    enabled: true
    ports:
      - port: 3030
        targetPort: 3030
        protocol: TCP
        name: http

lpr-web:
  enabled: true
  nameOverride: lpr-web

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment
    image:
      name: asia-southeast1-docker.pkg.dev/promrub-personal-use/promjodd/lpr-web
  service:
    enabled: true
    ports:
      - port: 3031
        targetPort: 3031
        protocol: TCP
        name: http
