envAlias: development
domainHttp: lp.promjodd-dev.prom.co.th
domainKafka: kafka-lp.promjodd-dev.prom.co.th
domainLprUpload: dev.promjodd.com

carpark-worker:
  ingress:
    enabled: false

  pods:
    env:
      # To solve ulimit(128) issue
      - name: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"

      - name: JAEGER_AGENT_HOST
        value: "http://tempo.tempo.svc.cluster.local"

      - name: JAEGER_AGENT_PORT
        value: "4317"

      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: "/credentials/gcloud-key.json"

      - name: LPRExecutor__lprBaseUrl
        valueFrom:
          secretKeyRef:
            name: lpr-worker-secret
            key: LPR_BASE_URL
            optional: false

      - name: LPRExecutor__lprAuthKey
        valueFrom:
          secretKeyRef:
            name: lpr-worker-secret
            key: LPR_AUTH_KEY
            optional: false


carpark-api:
  ingress:
    enabled: false

  pods:
    env:
      # To solve ulimit(128) issue
      - name: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"

      - name: DOTNET_ENVIRONMENT
        value: "Development"

      - name: JAEGER_AGENT_HOST
        value: "http://tempo.tempo.svc.cluster.local"

      - name: JAEGER_AGENT_PORT
        value: "4317"

      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: "/credentials/gcloud-key.json"

      - name: LPR__lprBaseUrl
        valueFrom:
          secretKeyRef:
            name: lpr-worker-secret
            key: LPR_BASE_URL
            optional: false

      - name: LPR__lprAuthKey
        valueFrom:
          secretKeyRef:
            name: lpr-worker-secret
            key: LPR_AUTH_KEY
            optional: false

      - name: PostgreSQL__Host
        value: "postgresql-lpr-api"

      - name: PostgreSQL__Database
        value: "lpr-api"

      - name: PostgreSQL__User
        value: "postgres"

      - name: PostgreSQL__Password
        valueFrom:
          secretKeyRef:
            name: lpr-api-postgres-secret
            key: adminPasswordKey
            optional: false

promjodd-web-portal:
  ingress:
    enabled: false

  pods:
    env:
      - name: LPR_KEY
        valueFrom:
          secretKeyRef:
            name: carpark-worker-secret
            key: LPR_UPLOADER_KEY
            optional: false

      - name: LPR_ENDPOINT
        value: https://lpr.promjodd-dev.prom.co.th/alpr/api/FileUpload/org/default/action/UploadVehicleImage
