{{ if eq .Values.envAlias "production" }}
# No DNS for development environment right now
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kong-http-cert
spec:
  secretName: kong-http-cert
  dnsNames:
    - {{ .Values.domainHttp }}
  issuerRef:
    name: lets-encrypt-issuer-prod
    kind: ClusterIssuer
    group: cert-manager.io
{{ end }}