apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kong-basic-auth
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: kong-basic-auth       # name of the k8s Secret to be created
  data:
  - secretKey: auth # MUST BE THIS NAME
    remoteRef:
      key: initial-secret
      property: SFTP_HOOK_AUTH_FILE
