apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true

    services:
    - name: lpr-api
      url: http://promjodd-v2-{{ .Values.envAlias }}-carpark-api:8080/
      routes:
      - name: alpr-api
        strip_path: true
        paths:
        - /alpr

    - name: lpr-uploader
      url: http://promjodd-v2-{{ .Values.envAlias }}-promjodd-web-portal:3030/
      routes:
      - name: alpr-uploader
        strip_path: false
        paths:
        - /web

    plugins:
    - name: http-log
      service: lpr-api
      config:
        http_endpoint: http://logstash-http-to-kafka.analytic-{{ .Values.envAlias }}.svc.cluster.local:8080/
        method: POST
        timeout: 1000
        keepalive: 1000
        flush_timeout: 2
        retry_count: 15
