apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lpr-web-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: lpr-web-secret      # name of the k8s Secret to be created
  data:
  - secretKey: LPR_ADMIN_API_KEY
    remoteRef:
      key: initial-secret
      property: LPR_ADMIN_API_KEY
