apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opensearch-admin-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store            # name of the SecretStore (or kind specified)
  target:
    name: opensearch-admin-secret     # name of the k8s Secret to be created
  data:
  - secretKey: username
    remoteRef:
      key: initial-secret
      property: GRAFANA_USER     # In the future we will use from another property

  - secretKey: password
    remoteRef:
      key: initial-secret
      property: GRAFANA_PASSWORD # In the future we will use from another property
