apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: webportal-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: webportal-secret      # name of the k8s Secret to be created
  data:
  - secretKey: IDP_CLIENT_ID
    remoteRef:
      key: initial-secret
      property: IDP_CLIENT_ID

  - secretKey: IDP_CLIENT_SECRET
    remoteRef:
      key: initial-secret
      property: IDP_CLIENT_SECRET

  - secretKey: IDP_ENDPOINT
    remoteRef:
      key: initial-secret
      property: IDP_ENDPOINT
