apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: promjodd-web-portal-cert
spec:
  secretName: promjodd-web-portal-cert
  dnsNames:
    - {{ .Values.domainLprUpload }}
    - www.{{ .Values.domainLprUpload }}
  issuerRef:
    name: lets-encrypt-issuer-prod
    kind: ClusterIssuer
    group: cert-manager.io
