apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vector-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: vector-credentials       # name of the k8s Secret to be created
  data:
  - secretKey: GRAFANA_LOKI_USER
    remoteRef:
      key: initial-secret
      property: GRAFANA_LOKI_USER

  - secretKey: GRAFANA_LOKI_PASSWORD
    remoteRef:
      key: initial-secret
      property: GRAFANA_LOKI_PASSWORD

  - secretKey: ENVIRONMENT
    remoteRef:
      key: initial-secret
      property: ENV
