apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ssh-private-key
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: ssh-secret-key        # name of the k8s Secret to be created
  data:
  - secretKey: ssh_host_rsa_key
    remoteRef:
      key: initial-secret
      property: SFTP_SSH_PRIVATE_KEY
